### ISSUE TITLE
Unable to run develop branch 

### ISSUE THREAD

**Issue by jacobofarrell** [snowplow/snowplow-elasticsearch-loader#111]
I'm attempting to use the develop branch due to the inclusion of #79 in order to utilise Elastic Cloud. 

Trying to run the current develop build using the instructions specified in the readme. However it appears the application doesn't take arguments at present, so we have hard-coded past this. After this, we run into the following issue: 

```
[info] Running com.snowplowanalytics.stream.loader.ElasticsearchStreamLoaderApp
null
[error] (run-main-0) java.lang.ExceptionInInitializerError
[error] java.lang.ExceptionInInitializerError
[error]         at com.snowplowanalytics.stream.loader.ElasticsearchStreamLoaderApp.main(ElasticsearchStreamLoaderApp.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.Run.invokeMain(Run.scala:93)
[error]         at sbt.Run.run0(Run.scala:87)
[error]         at sbt.Run.execute$1(Run.scala:65)
[error]         at sbt.Run.$anonfun$run$4(Run.scala:77)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error]         at sbt.TrapExit$App.run(TrapExit.scala:252)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] Caused by: com.amazonaws.SdkClientException: Unable to marshall request to JSON: Jackson jackson-core/jackson-dataformat-cbor incompatible library version detected.
[error] You have two possible resolutions:
[error]                 1) Ensure the com.fasterxml.jackson.core:jackson-core & com.fasterxml.jackson.dataformat:jackson-dataformat-cbor libraries on your classpath have the same version number
[error]                 2) Disable CBOR wire-protocol by passing the -Dcom.amazonaws.sdk.disableCbor property or setting the AWS_CBOR_DISABLE environment variable (warning this may affect performance)
[error]         at com.amazonaws.services.kinesis.model.transform.DescribeStreamRequestProtocolMarshaller.marshall(DescribeStreamRequestProtocolMarshaller.java:58)
[error]         at com.amazonaws.services.kinesis.AmazonKinesisClient.executeDescribeStream(AmazonKinesisClient.java:744)
[error]         at com.amazonaws.services.kinesis.AmazonKinesisClient.describeStream(AmazonKinesisClient.java:729)
[error]         at com.amazonaws.services.kinesis.AmazonKinesisClient.describeStream(AmazonKinesisClient.java:766)
[error]         at com.snowplowanalytics.stream.loader.sinks.KinesisSink.streamExists(KinesisSink.scala:79)
[error]         at com.snowplowanalytics.stream.loader.sinks.KinesisSink.<init>(KinesisSink.scala:68)
[error]         at com.snowplowanalytics.stream.loader.StreamLoaderApp.$init$(StreamLoaderApp.scala:121)
[error]         at com.snowplowanalytics.stream.loader.ElasticsearchStreamLoaderApp$.<init>(ElasticsearchStreamLoaderApp.scala:34)
[error]         at com.snowplowanalytics.stream.loader.ElasticsearchStreamLoaderApp$.<clinit>(ElasticsearchStreamLoaderApp.scala)
[error]         at com.snowplowanalytics.stream.loader.ElasticsearchStreamLoaderApp.main(ElasticsearchStreamLoaderApp.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.Run.invokeMain(Run.scala:93)
[error]         at sbt.Run.run0(Run.scala:87)
[error]         at sbt.Run.execute$1(Run.scala:65)
[error]         at sbt.Run.$anonfun$run$4(Run.scala:77)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error]         at sbt.TrapExit$App.run(TrapExit.scala:252)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.lang.RuntimeException: Jackson jackson-core/jackson-dataformat-cbor incompatible library version detected.
[error] You have two possible resolutions:
[error]                 1) Ensure the com.fasterxml.jackson.core:jackson-core & com.fasterxml.jackson.dataformat:jackson-dataformat-cbor libraries on your classpath have the same version number
[error]                 2) Disable CBOR wire-protocol by passing the -Dcom.amazonaws.sdk.disableCbor property or setting the AWS_CBOR_DISABLE environment variable (warning this may affect performance)
[error]         at com.amazonaws.protocol.json.SdkCborGenerator.getBytes(SdkCborGenerator.java:68)
[error]         at com.amazonaws.protocol.json.internal.JsonProtocolMarshaller.finishMarshalling(JsonProtocolMarshaller.java:188)
[error]         at com.amazonaws.protocol.json.internal.NullAsEmptyBodyProtocolRequestMarshaller.finishMarshalling(NullAsEmptyBodyProtocolRequestMarshaller.java:53)
[error]         at com.amazonaws.services.kinesis.model.transform.DescribeStreamRequestProtocolMarshaller.marshall(DescribeStreamRequestProtocolMarshaller.java:56)
[error]         at com.amazonaws.services.kinesis.AmazonKinesisClient.executeDescribeStream(AmazonKinesisClient.java:744)
[error]         at com.amazonaws.services.kinesis.AmazonKinesisClient.describeStream(AmazonKinesisClient.java:729)
[error]         at com.amazonaws.services.kinesis.AmazonKinesisClient.describeStream(AmazonKinesisClient.java:766)
[error]         at com.snowplowanalytics.stream.loader.sinks.KinesisSink.streamExists(KinesisSink.scala:79)
[error]         at com.snowplowanalytics.stream.loader.sinks.KinesisSink.<init>(KinesisSink.scala:68)
[error]         at com.snowplowanalytics.stream.loader.StreamLoaderApp.$init$(StreamLoaderApp.scala:121)
[error]         at com.snowplowanalytics.stream.loader.ElasticsearchStreamLoaderApp$.<init>(ElasticsearchStreamLoaderApp.scala:34)
[error]         at com.snowplowanalytics.stream.loader.ElasticsearchStreamLoaderApp$.<clinit>(ElasticsearchStreamLoaderApp.scala)
[error]         at com.snowplowanalytics.stream.loader.ElasticsearchStreamLoaderApp.main(ElasticsearchStreamLoaderApp.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.Run.invokeMain(Run.scala:93)
[error]         at sbt.Run.run0(Run.scala:87)
[error]         at sbt.Run.execute$1(Run.scala:65)
[error]         at sbt.Run.$anonfun$run$4(Run.scala:77)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error]         at sbt.TrapExit$App.run(TrapExit.scala:252)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.dataformat.cbor.CBORGenerator.getOutputContext()Lcom/fasterxml/jackson/core/json/JsonWriteContext;
[error]         at com.fasterxml.jackson.dataformat.cbor.CBORGenerator.close(CBORGenerator.java:903)
[error]         at com.amazonaws.protocol.json.SdkJsonGenerator.close(SdkJsonGenerator.java:253)
[error]         at com.amazonaws.protocol.json.SdkJsonGenerator.getBytes(SdkJsonGenerator.java:268)
[error]         at com.amazonaws.protocol.json.SdkCborGenerator.getBytes(SdkCborGenerator.java:66)
[error]         at com.amazonaws.protocol.json.internal.JsonProtocolMarshaller.finishMarshalling(JsonProtocolMarshaller.java:188)
[error]         at com.amazonaws.protocol.json.internal.NullAsEmptyBodyProtocolRequestMarshaller.finishMarshalling(NullAsEmptyBodyProtocolRequestMarshaller.java:53)
[error]         at com.amazonaws.services.kinesis.model.transform.DescribeStreamRequestProtocolMarshaller.marshall(DescribeStreamRequestProtocolMarshaller.java:56)
[error]         at com.amazonaws.services.kinesis.AmazonKinesisClient.executeDescribeStream(AmazonKinesisClient.java:744)
[error]         at com.amazonaws.services.kinesis.AmazonKinesisClient.describeStream(AmazonKinesisClient.java:729)
[error]         at com.amazonaws.services.kinesis.AmazonKinesisClient.describeStream(AmazonKinesisClient.java:766)
[error]         at com.snowplowanalytics.stream.loader.sinks.KinesisSink.streamExists(KinesisSink.scala:79)
[error]         at com.snowplowanalytics.stream.loader.sinks.KinesisSink.<init>(KinesisSink.scala:68)
[error]         at com.snowplowanalytics.stream.loader.StreamLoaderApp.$init$(StreamLoaderApp.scala:121)
[error]         at com.snowplowanalytics.stream.loader.ElasticsearchStreamLoaderApp$.<init>(ElasticsearchStreamLoaderApp.scala:34)
[error]         at com.snowplowanalytics.stream.loader.ElasticsearchStreamLoaderApp$.<clinit>(ElasticsearchStreamLoaderApp.scala)
[error]         at com.snowplowanalytics.stream.loader.ElasticsearchStreamLoaderApp.main(ElasticsearchStreamLoaderApp.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.Run.invokeMain(Run.scala:93)
[error]         at sbt.Run.run0(Run.scala:87)
[error]         at sbt.Run.execute$1(Run.scala:65)
[error]         at sbt.Run.$anonfun$run$4(Run.scala:77)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error]         at sbt.TrapExit$App.run(TrapExit.scala:252)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error]         at sbt.Run$.executeTrapExit(Run.scala:124)
[error]         at sbt.Run.run(Run.scala:77)
[error]         at sbt.Defaults$.$anonfun$bgRunTask$5(Defaults.scala:1174)
[error]         at sbt.Defaults$.$anonfun$bgRunTask$5$adapted(Defaults.scala:1169)
[error]         at sbt.internal.BackgroundThreadPool.$anonfun$run$1(DefaultBackgroundJobService.scala:366)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at scala.util.Try$.apply(Try.scala:209)
[error]         at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:289)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (Compile / run) Nonzero exit code: 1
[error] Total time: 5 s, completed Aug 1, 2018 4:46:32 AM
```

Any help would be appreciated! Hopefully I'm just doing something wrong!

**Comment by BenFradet** [comment]
It seems we've introduced a dependency conflict in the recent dependency bumps.
Until this issue is resolved, you can use the `-Dcom.amazonaws.sdk.disableCbor` jvm flag.

**Comment by szareiangm** [comment]
This is unexpected to me. Perhaps I missed some code in our develop branch. I will check this issue tomorrow morning.

**Comment by szareiangm** [comment]
So the issue sort of complicated and I am not sure why I didn't notice when updating the dependencies. 
There is Jackson both in AWS dependencies and elastic4s. Fixing the first one is straight-forward and classic. However, when fixing it for the first one, the second one end up in an internal library error for `ArrayOutOfBoundException`. I have spent some time yesterday on it and I will find a solution for it soon.

**Comment by szareiangm** [comment]
The problem was that both `AWS Kinesis library` and `elastic4s` were using Jackson and fixing the AWS library exception causes the issue with elastic4s. 

So I made the changes below during my journey to fix it: 
- Used `elastic4s-circle` instead of default (Jackson) to reduce headache and dependency to Jackson
- Adding `jacksonDatabind` and `jacksonCbor` for the AWS dependency side.
- Bump elastic4s and Elasticsearch library to 6.3 because the latest one is very compelling (comes with lots of goodies like SQL support). Just as a bonus.

@BenFradet When I am submitting my fix, should I put first two in one commit and the last in another with separate issue? I still need to do integration testing but it is almost 8pm and gotta leave the office. Will do it in the morning with the commits separation.

**Comment by szareiangm** [comment]
For some reason elastic4s 6.3.6 and jackson 2.9.6 were not happy with parsing elastic4s BulkResponse objects. I found this solution it worked in my integration test. Will submit the PR tomorrow.
