### ISSUE TITLE
nsq consumer error 

### ISSUE THREAD

**Issue by sushantbprise** [snowplow/snowplow-elasticsearch-loader#125]
Hi all,
Need help for below error,

`[nioEventLoopGroup-2-1] ERROR com.snowplowanalytics.elasticsearch.loader.NsqSourceExecutor - Exception while consuming topic goodout
com.snowplowanalytics.client.nsq.exceptions.NSQException: E_TOUCH_FAILED TOUCH 0a9f71612c16401b failed ID not in flight
	at com.snowplowanalytics.client.nsq.exceptions.NSQException.of(NSQException.java:23)
	at com.snowplowanalytics.client.nsq.Connection.incoming(Connection.java:127)
	at com.snowplowanalytics.client.nsq.netty.NSQHandler.lambda$channelRead0$0(NSQHandler.java:41)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:745)
[nioEventLoopGroup-2-1] WARN io.netty.util.concurrent.AbstractEventExecutor - A task raised an exception. Task: com.snowplowanalytics.client.nsq.netty.NSQHandler$$Lambda$3/824543941@4a96cd95
java.lang.IllegalStateException: Queue full
	at java.util.AbstractQueue.add(AbstractQueue.java:98)
	at com.snowplowanalytics.client.nsq.Connection.incoming(Connection.java:129)
	at com.snowplowanalytics.client.nsq.netty.NSQHandler.lambda$channelRead0$0(NSQHandler.java:41)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:745)
[nioEventLoopGroup-2-1] ERROR com.snowplowanalytics.elasticsearch.loader.NsqSourceExecutor - Exception while consuming topic goodout
com.snowplowanalytics.client.nsq.exceptions.NSQException: E_FIN_FAILED FIN 0a9f71612c16401b failed ID not in flight
	at com.snowplowanalytics.client.nsq.exceptions.NSQException.of(NSQException.java:23)
	at com.snowplowanalytics.client.nsq.Connection.incoming(Connection.java:127)
	at com.snowplowanalytics.client.nsq.netty.NSQHandler.lambda$channelRead0$0(NSQHandler.java:41)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:745)
[nioEventLoopGroup-2-1] WARN io.netty.util.concurrent.AbstractEventExecutor - A task raised an exception. Task: com.snowplowanalytics.client.nsq.netty.NSQHandler$$Lambda$3/824543941@13119927
java.lang.IllegalStateException: Queue full
	at java.util.AbstractQueue.add(AbstractQueue.java:98)
	at com.snowplowanalytics.client.nsq.Connection.incoming(Connection.java:129)
	at com.snowplowanalytics.client.nsq.netty.NSQHandler.lambda$channelRead0$0(NSQHandler.java:41)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by BenFradet** [comment]
Your loader as a NSQ consumer is timing out on responding to nsqd, your incoming connection queue is also full.

I'm assuming there is some kind of network issue.
