### ISSUE TITLE
2.0.5 version is not recovering on 429 error

### ISSUE THREAD

**Issue by arthur78** [snowplow/snowplow-elasticsearch-loader#233]
2022-06-03 19:00:21:470 +0000 [RecordProcessor-0000] ERROR com.snowplowanalytics.stream.loader.clients.ElasticsearchBulkSender - Shutting down application as unable to connect to Elasticsearch for over 60000 ms
java.util.NoSuchElementException: Request Failure ElasticError(429,429,None,None,None,List(),None,None,None,List())
        at com.sksamuel.elastic4s.RequestFailure.result(responses.scala:75)
        at com.sksamuel.elastic4s.RequestFailure.result(responses.scala:71)
        at com.snowplowanalytics.stream.loader.clients.ElasticsearchBulkSender.extractResult(ElasticsearchBulkSender.scala:171)
        at com.snowplowanalytics.stream.loader.clients.ElasticsearchBulkSender.$anonfun$send$6(ElasticsearchBulkSender.scala:136)
        at unsafeRunSync @ com.snowplowanalytics.stream.loader.clients.ElasticsearchBulkSender.send(ElasticsearchBulkSender.scala:136)
        at fromFuture @ com.snowplowanalytics.stream.loader.clients.BulkSender$.futureToTask(BulkSender.scala:137)
        at unsafeRunSync @ com.snowplowanalytics.stream.loader.clients.ElasticsearchBulkSender.send(ElasticsearchBulkSender.scala:136)
        at fromFuture @ com.snowplowanalytics.stream.loader.clients.BulkSender$.futureToTask(BulkSender.scala:137)
        at map @ com.snowplowanalytics.stream.loader.clients.ElasticsearchBulkSender.send(ElasticsearchBulkSender.scala:136)
2022-06-03 19:00:21:472 +0000 [RecordProcessor-0000] INFO com.snowplowanalytics.stream.loader.clients.ElasticsearchBulkSender - BulkSender force shutdown

**Comment by istreeter** [comment]
Hi @arthur78 thanks for reporting this.  I agree there is a bug here to be fixed.

I'll make some notes here, but this is mainly for my own benefit:

The error message is coming from [this line](https://github.com/snowplow/snowplow-elasticsearch-loader/blob/2.0.6/elasticsearch/src/main/scala/com/snowplowanalytics/stream/loader/clients/ElasticsearchBulkSender.scala#L171).  It is not valid to call `.result` on the response [if the response was an error](https://github.com/sksamuel/elastic4s/blob/v7.14.1/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/responses.scala#L75).  We can make this error message nicer by pattern matching on the response type, and handling an error response explicitly.

A bigger problem, though, is that we are handling the error response **after** [the cats retry logic](https://github.com/snowplow/snowplow-elasticsearch-loader/blob/2.0.6/elasticsearch/src/main/scala/com/snowplowanalytics/stream/loader/clients/ElasticsearchBulkSender.scala#L135).  So if we get an error response on the first attempt (with no exception) then we never retry to index the events.  We should fix this by making the cats-retry logic handle retrying if the response is an exception.

After that....  if the app still gets error responses even after the max number of attempts.... then it is probably the correct thing to crash the app.  This would be better than sending all events to the bad stream in the case that elasticsearch is unavailable.  This will be consistent with Snowplow's other streaming loaders, (e.g. BigQuery Loader) which also retry loads a few times and then crash the app in extreme circumstances when the target is not available.
